version: "3"
services:

  db:
    image: postgres
    expose:
    - "5432"
    ports:
    - "5435:5432"
    environment:
    - POSTGRES_DB=ruby_benchmark_development
    - POSTGRES_USER=ruby_benchmark
    - POSTGRES_PASSWORD=password
  web:
    build: .
    volumes:
      - .:/ruby_benchmark
    ports:
      - "3000:3000"
    depends_on:
      - db