version: "3"
services:

  db:
    image: postgres
    volumes:
      - ~/docker/volumes/postgresql:/var/lib/postgresql/data
    expose:
    - "5432"
    ports:
    - "5435:5432"
    environment:
    - POSTGRES_DB=ruby_benchmark_development
    - POSTGRES_USER=ruby_benchmark
    - POSTGRES_PASSWORD=password
  web:
    build: .
    volumes:
      - .:/ruby_benchmark
    ports:
      - "3000:3000"
    depends_on:
     - db
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
  redis:
    image: redis
    command: "redis-server"
    ports:
      - "6379:6379"
    volumes:
      - ~/docker/volumes/redis:/data
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
  sidekiq:
    build: .
    command: "bundle exec sidekiq -r ./worker.rb"
    volumes:
      - .:/ruby_benchmark
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    depends_on:
      - redis