version: "3"

services:

  db:
    image: postgres
    volumes:
      - ~/docker/volumes/ruby_benchmark/postgresql:/var/lib/postgresql/data
    hostname: "db"
    expose:
      - "5432"
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=ruby_benchmark_dev
      - POSTGRES_USER=ruby_benchmark_dev
      - POSTGRES_PASSWORD=ruby_benchmark_dev

  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - .:/ruby_benchmark
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - APP_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ruby_benchmark_dev
      - POSTGRES_USER=ruby_benchmark_dev
      - POSTGRES_PASSWORD=ruby_benchmark_dev
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    command: bash -c "bundle exec rerun --background \"rackup config.ru --host 0.0.0.0 --port 3000\""

  redis:
    image: redis
    volumes:
      - ~/docker/volumes/ruby_benchmark/redis:/data
    hostname: "redis"
    ports:
      - "6379:6379"
    command: "redis-server"

  sidekiq:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/ruby_benchmark
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    depends_on:
      - redis
    command: bash -c "bundle exec sidekiq -r ./worker.rb | tee -a ./log/sidekiq-development.log"
